[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.model_checker]
contracts = { '/path/to/project/src/MyContract.sol' = [ 'Contract' ] }
engine = 'chc'
targets = [ 'assert' ]

solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
verbosity = 2

# Test specific settings
[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Gas settings
gas_limit = 9223372036854775807
gas_price = 0
block_gas_limit = 30000000

# RPC settings
eth_rpc_url = "${ETH_RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# Compiler settings
via_ir = false
bytecode_hash = "none"
cbor_metadata = false